version: "3"
services:
  hugo:
    container_name: hugo
    # image: peaceiris/hugo:v0.x.x-mod   # Hugo Modules
    # image: peaceiris/hugo:v0.x.x-full  # Hugo Modules and Node.js
    image: peaceiris/hugo:v0.80.0-mod
    working_dir: /home/hugo
    volumes:
      - .:/home/hugo
    ports:
      - 1313:1313
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts

  netlify-cms-proxy-server:
    container_name: netlify-cms-proxy-server
    image: node:15.8.0-alpine3.12
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    command:
      - npx
      - netlify-cms-proxy-server
